### ISSUE TITLE
Add gitter badge to readme (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/website#1]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)
- [Community](https://github.com/DAVFoundation/community/labels/first-timers-only)
- [community-client](https://github.com/DAVFoundation/community-client/labels/first-timers-only)
- [website](https://github.com/DAVFoundation/website/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Website

The DAV project you are looking at is Website. It is the source of https://dav.network

### The Issue

Your task for this issue is to add the gitter button which links to the DAV-contributors gitter chat room in the `README.md` file.
Just add the below lines in the `README.md` and look at other DAV project's README.md for the location.
````markdown
[![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)
````

### Contributing to Community

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Community GitHub page](https://github.com/DAVFoundation/website).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/website.git`
- [ ] **Make changes in the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/website](https://github.com/YOUR-USER-NAME/website)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by tsmanikandan** [comment]
I can take this one

**Comment by cg-cnu** [comment]
Hey @tsmanikandan Thanks for your interest. Go ahead, Its yours 😄

**Comment by cg-cnu** [comment]
Hey @tsmanikandan Congratulations on your first contribution to open-source 🎆 We really appreciate taking the time to work on this issue. We hope you contribute more to open-source in the future. 😄 
Sorry for getting back to you so late. I missed closing this pr. Free free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) where you can find more opportunities 🙂
