### ISSUE TITLE
Add code of conduct (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/website#3]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)
- [Community](https://github.com/DAVFoundation/community/labels/first-timers-only)
- [community-client](https://github.com/DAVFoundation/community-client/labels/first-timers-only)
- [website](https://github.com/DAVFoundation/website/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Website

The DAV project you are looking at is Website. Website is the source of https://dav.network

### The Issue

To help create an open and welcoming environment, we would like to have a code of conduct document as part of this project.

Please add a file called `code_of_conduct.md` to the root of the project. This file should be based on the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md). Please update the document with `tal@dav.network`  instead of the placeholder email address.

### Contributing to Community

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Community GitHub page](https://github.com/DAVFoundation/website).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/website.git`
- [ ] **Make changes in the code_of_conduct.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/website](https://github.com/YOUR-USER-NAME/website)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by ModifiedChocolateUnicorn** [comment]
Hello there, I never contributed to an open source project so I'd like trying to do it by helping on this issue please =) ! (If I understood well, we have to take the content of the conduct code file and put it inside a code_of_conduct.md file).

**Comment by TalAter** [comment]
Yes, sounds like you understood it perfectly 👍 

Just read the issue carefully, including the instructions, and you should be all good!
@cg-cnu and myself can help you with any questions you might have!

Thank you for taking the time to contribute to open source ❤️

**Comment by ModifiedChocolateUnicorn** [comment]
Just to be 100% sure, @TalAter do I create the file (code_of_conduct.md) at the root of the folder (that's what I did for now supposing this was the idea) ?

**Comment by cg-cnu** [comment]
@ModifiedChocolateUnicorn Absolutely, you are right 😄

**Comment by ModifiedChocolateUnicorn** [comment]
Well @cg-cnu I did reread the steps but forgot that the file's location was mentionned before. So I deleted the question that was useless after seeing that (and creating the file at the root of the folder even before asking (but I wanted to be 100% sure, hence why the question)). Thank you 😄 .

**Comment by ModifiedChocolateUnicorn** [comment]
Would this PR be good enough ? 
![image](https://user-images.githubusercontent.com/20042260/32565520-59930ec2-c4b7-11e7-8148-d180824c28b4.png)

**Comment by cg-cnu** [comment]
Hey @ModifiedChocolateUnicorn The Pull Request template is supposed to help people by reminding them to do certain things before making PR and what information to fill in while making the PR. Sorry that its a little confusing to you. But, that's a necessary evil we have to deal with to get the relevant information possible in all the cases. In your case, it an improvement you are making with out any code change. So most of them like tests and code style won't apply. You can leave it as it is now. But, now know why there is a PR template and how you can use it in your future PRs. 🙂
Now go ahead and make your first PR 🎉 😄

**Comment by ModifiedChocolateUnicorn** [comment]
Hey @cg-cnu, it's now done. Well, I knew this was a template but I wasn't sure what ideal (removing standard content from the non useful parts but keep the title, remove everything even the title of the section or let everything as is except the parts I need. Yay 🎊 !

**Comment by cg-cnu** [comment]
Hey @ModifiedChocolateUnicorn Congratulations 🍾  You did it 🎉  💯  We really appreciate taking the time to work on this issue. We hope this will get you started on contributing more to open source. Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) 😄
